# docker-compose.yml
version: "3"
services:
  database_development:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_DB=aema-development
      - POSTGRES_USER=aema
      - POSTGRES_PASSWORD=aema
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5431:5432
  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  database-data: # named volumes can be managed easier using docker-compose
